**Set environment**

In [1]:
import numpy  as np
import pandas as pd
import os
import pickle

In [2]:
%run ../run_config_project.py
show_env()

BASE DIRECTORY (FD_BASE): /hpc/group/igvf/kk319
REPO DIRECTORY (FD_REPO): /hpc/group/igvf/kk319/repo
WORK DIRECTORY (FD_WORK): /hpc/group/igvf/kk319/work
DATA DIRECTORY (FD_DATA): /hpc/group/igvf/kk319/data


You are working with      IGVF BlueSTARR
PATH OF PROJECT (FD_PRJ): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR
PROJECT RESULTS (FD_RES): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results
PROJECT SCRIPTS (FD_EXE): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/scripts
PROJECT DATA    (FD_DAT): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data
PROJECT NOTE    (FD_NBK): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/notebooks
PROJECT DOCS    (FD_DOC): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/docs
PROJECT LOG     (FD_LOG): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/log
PROJECT REF     (FD_REF): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/references



In [3]:
import fun_meme as mymeme

## Import data

In [4]:
!ls $FD_DATA

genome				   motif_nonredundant_jvierstra_v2.0beta
motif_jaspar2024		   motif_nonredundant_jvierstra_v2.1beta
motif_nonredundant_jvierstra_v1.0


### Import Motifs from JASPAR2024

**Check data**

In [5]:
!ls $FD_DATA/motif_jaspar2024

JASPAR2024_CORE_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_non-redundant_pfms_meme.zip
JASPAR2024_CORE_non-redundant_pfms_transfac.zip
JASPAR2024_CORE_vertebrates_meme
JASPAR2024_CORE_vertebrates_non-redundant.meme
JASPAR2024_CORE_vertebrates_non-redundant.meme.pkl
JASPAR2024_CORE_vertebrates_non-redundant.npz
JASPAR2024_CORE_vertebrates_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_meme.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_transfac.zip


In [6]:
!head -n 20 $FD_DATA/motif_jaspar2024/JASPAR2024_CORE_vertebrates_non-redundant.meme

MEME version 4

ALPHABET= ACGT

strands: + -

Background letter frequencies
A 0.25 C 0.25 G 0.25 T 0.25

MOTIF MA0002.3 Runx1
letter-probability matrix: alength= 4 w= 9 nsites= 2000 E= 0
 0.061500  0.536000  0.074500  0.328000
 0.028500  0.000000  0.003500  0.968000
 0.000000  0.037500  0.936000  0.026500
 0.043500  0.063500  0.035000  0.858000
 0.000000  0.000000  0.993500  0.006500
 0.008500  0.021000  0.924000  0.046500
 0.005000  0.200000  0.125500  0.669500
 0.065500  0.231500  0.040500  0.662500
 0.250000  0.079000  0.144500  0.526500


**Import data**

In [7]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_jaspar2024")
txt_fname = "JASPAR2024_CORE_vertebrates_non-redundant.meme"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
dct_motif_jaspar = mymeme.read_meme(txt_fpath)

**Summarize data**

In [8]:
dct_motif = dct_motif_jaspar.copy()
first_key = next(iter(dct_motif))
first_pwm = dct_motif[first_key]

print("Type:",       type(dct_motif))
print("Num motifs:", len(dct_motif))
print("First motif key:",    first_key)
print("First PWM shape:",    first_pwm.shape)
print("First 3 rows:\n",     first_pwm[:3])
print("Row sums (first 3):", first_pwm[:3].sum(axis=1))

Type: <class 'dict'>
Num motifs: 879
First motif key: MA0002.3 Runx1
First PWM shape: (9, 4)
First 3 rows:
 [[0.0615 0.536  0.0745 0.328 ]
 [0.0285 0.     0.0035 0.968 ]
 [0.     0.0375 0.936  0.0265]]
Row sums (first 3): [1. 1. 1.]


In [9]:
arr_len = np.array([pwm.shape[0] for pwm in dct_motif_jaspar.values()])

print("Motif length statistics")
print("  count :", arr_len.size)
print("  min   :", arr_len.min())
print("  25%   :", np.percentile(arr_len, 25))
print("  median:", np.median(arr_len))
print("  mean  :", arr_len.mean())
print("  75%   :", np.percentile(arr_len, 75))
print("  max   :", arr_len.max())

Motif length statistics
  count : 879
  min   : 5
  25%   : 8.0
  median: 9.0
  mean  : 10.091012514220706
  75%   : 12.0
  max   : 33


### Import Motifs from jvierstra

**Check data**

In [10]:
!ls $FD_DATA/motif_nonredundant_jvierstra_v2.1beta

all.dbs.meme.pkl  consensus_pwms.meme.pkl  metadata.tsv
all.dbs.meme.txt  consensus_pwms.meme.txt  tomtom.all.txt


In [11]:
!head -n 20 $FD_DATA/motif_nonredundant_jvierstra_v2.1beta/consensus_pwms.meme.txt

MEME version 4

ALPHABET= ACGT

strands: + -

Background letter frequencies (from uniform background):
A 0.25000 C 0.25000 G 0.25000 T 0.25000 

MOTIF AC0001:GATA/PROP:GATA AC0001:GATA/PROP:GATA

letter-probability matrix: alength= 4 w= 13 nsites= 20 E= 0
  0.676859	  0.103120	  0.104093	  0.115927	
  0.023893	  0.035573	  0.009097	  0.931437	
  0.934550	  0.021763	  0.019600	  0.024087	
  0.917327	  0.041030	  0.018193	  0.023450	
  0.038483	  0.317794	  0.210558	  0.433165	
  0.190786	  0.100360	  0.553218	  0.155636	
  0.303647	  0.276917	  0.157037	  0.262400	
  0.193229	  0.356892	  0.190209	  0.259669	


In [12]:
!head -n 20 $FD_DATA/motif_nonredundant_jvierstra_v2.1beta/all.dbs.meme.txt

MEME version 4.12.0

ALPHABET= ACGT

strands: + -

Background letter frequencies (from unknown source):
 A 0.250 C 0.250 G 0.250 T 0.250

MOTIF BANP_Grand2021

letter-probability matrix: alength= 4 w= 10 nsites= 20 E= 0.0e+000
 0.016833  0.109833  0.039833  0.833500
 0.149500  0.792500  0.041667  0.016333
 0.034833  0.090833  0.036000  0.838333
 0.001000  0.986000  0.005167  0.007833
 0.016333  0.001833  0.975667  0.006167
 0.006167  0.975667  0.001833  0.016333
 0.007833  0.005167  0.986000  0.001000
 0.838333  0.036000  0.090833  0.034833


**Import data**

In [13]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_nonredundant_jvierstra_v2.1beta")
txt_fname = "consensus_pwms.meme.txt"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
dct_motif_jvierstra_consensus = mymeme.read_meme(txt_fpath)

In [14]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_nonredundant_jvierstra_v2.1beta")
txt_fname = "all.dbs.meme.txt"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
dct_motif_jvierstra_total = mymeme.read_meme(txt_fpath)

**Summarize data**

In [15]:
dct_motif = dct_motif_jvierstra_consensus.copy()
first_key = next(iter(dct_motif))
first_pwm = dct_motif[first_key]

print("Type:",       type(dct_motif))
print("Num motifs:", len(dct_motif))
print("First motif key:",    first_key)
print("First PWM shape:",    first_pwm.shape)
print("First 3 rows:\n",     first_pwm[:3])
print("Row sums (first 3):", first_pwm[:3].sum(axis=1))

Type: <class 'dict'>
Num motifs: 637
First motif key: AC0001:GATA/PROP:GATA AC0001:GATA/PROP:GATA
First PWM shape: (13, 4)
First 3 rows:
 [[0.676859 0.10312  0.104093 0.115927]
 [0.023893 0.035573 0.009097 0.931437]
 [0.93455  0.021763 0.0196   0.024087]]
Row sums (first 3): [0.999999 1.       1.      ]


In [16]:
arr_len = np.array([pwm.shape[0] for pwm in dct_motif_jvierstra_consensus.values()])

print("Motif length statistics")
print("  count :", arr_len.size)
print("  min   :", arr_len.min())
print("  25%   :", np.percentile(arr_len, 25))
print("  median:", np.median(arr_len))
print("  mean  :", arr_len.mean())
print("  75%   :", np.percentile(arr_len, 75))
print("  max   :", arr_len.max())

Motif length statistics
  count : 637
  min   : 4
  25%   : 8.0
  median: 11.0
  mean  : 12.320251177394034
  75%   : 15.0
  max   : 28


In [17]:
dct_motif = dct_motif_jvierstra_total.copy()
first_key = next(iter(dct_motif))
first_pwm = dct_motif[first_key]

print("Type:",       type(dct_motif))
print("Num motifs:", len(dct_motif))
print("First motif key:",    first_key)
print("First PWM shape:",    first_pwm.shape)
print("First 3 rows:\n",     first_pwm[:3])
print("Row sums (first 3):", first_pwm[:3].sum(axis=1))

Type: <class 'dict'>
Num motifs: 5301
First motif key: BANP_Grand2021
First PWM shape: (10, 4)
First 3 rows:
 [[0.016833 0.109833 0.039833 0.8335  ]
 [0.1495   0.7925   0.041667 0.016333]
 [0.034833 0.090833 0.036    0.838333]]
Row sums (first 3): [0.999999 1.       0.999999]


In [18]:
arr_len = np.array([pwm.shape[0] for pwm in dct_motif_jvierstra_total.values()])

print("Motif length statistics")
print("  count :", arr_len.size)
print("  min   :", arr_len.min())
print("  25%   :", np.percentile(arr_len, 25))
print("  median:", np.median(arr_len))
print("  mean  :", arr_len.mean())
print("  75%   :", np.percentile(arr_len, 75))
print("  max   :", arr_len.max())

Motif length statistics
  count : 5301
  min   : 5
  25%   : 10.0
  median: 12.0
  mean  : 12.847764572722127
  75%   : 15.0
  max   : 39


In [19]:
arr_len = np.array([pwm.shape[0] for pwm in dct_motif_jvierstra_total.values()])
print(sum(arr_len > 30))
print(sum(arr_len > 35))

8
3


## Store the motif dictionaries as pickle files

In [20]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_jaspar2024")
txt_fname = "JASPAR2024_CORE_vertebrates_non-redundant.meme.pkl"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
with open(txt_fpath, "wb") as file:
    pickle.dump(dct_motif_jaspar, file, protocol=pickle.HIGHEST_PROTOCOL)

In [21]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_nonredundant_jvierstra_v2.1beta")
txt_fname = "consensus_pwms.meme.pkl"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
with open(txt_fpath, "wb") as file:
    pickle.dump(dct_motif_jvierstra_consensus, file, protocol=pickle.HIGHEST_PROTOCOL)

In [22]:
### set file directory
txt_fdiry = os.path.join(FD_DATA, "motif_nonredundant_jvierstra_v2.1beta")
txt_fname = "all.dbs.meme.pkl"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import meme file
with open(txt_fpath, "wb") as file:
    pickle.dump(dct_motif_jvierstra_total, file, protocol=pickle.HIGHEST_PROTOCOL)