**Set environment**

In [1]:
import numpy as np

In [2]:
%run ../run_config_project.py
show_env()

BASE DIRECTORY (FD_BASE): /hpc/group/igvf/kk319
REPO DIRECTORY (FD_REPO): /hpc/group/igvf/kk319/repo
WORK DIRECTORY (FD_WORK): /hpc/group/igvf/kk319/work
DATA DIRECTORY (FD_DATA): /hpc/group/igvf/kk319/data


You are working with      IGVF BlueSTARR
PATH OF PROJECT (FD_PRJ): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR
PROJECT RESULTS (FD_RES): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results
PROJECT SCRIPTS (FD_EXE): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/scripts
PROJECT DATA    (FD_DAT): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data
PROJECT NOTE    (FD_NBK): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/notebooks
PROJECT DOCS    (FD_DOC): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/docs
PROJECT LOG     (FD_LOG): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/log
PROJECT REF     (FD_REF): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/references



## Import data

**Check file existence**

In [3]:
%env FD_DATA={FD_DATA}
%env FD_RES={FD_RES}

env: FD_DATA=/hpc/group/igvf/kk319/data
env: FD_RES=/hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results


In [4]:
%%bash
ls ${FD_DATA}/jaspar2024

JASPAR2024_CORE_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_non-redundant_pfms_meme.zip
JASPAR2024_CORE_non-redundant_pfms_transfac.zip
JASPAR2024_CORE_vertebrates_meme
JASPAR2024_CORE_vertebrates_non-redundant.meme
JASPAR2024_CORE_vertebrates_non-redundant.npz
JASPAR2024_CORE_vertebrates_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_meme.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_transfac.zip


In [5]:
%%bash
ls ${FD_RES}/analysis_variant_motif_richard

background_zero_order.npy
background_zero_order.tsv
batches_dev
JASPAR2024_CORE_vertebrates_non-redundant.lods.npz
JASPAR2024_CORE_vertebrates_non-redundant.pmap.npz
test_seq.fa
test_seq.fa.fai
test_variants.fa
test_variants.fa.fai
variant_closed_gof_bluestarr_flank35_obs.fa
variant_closed_gof_bluestarr_flank35_ref.fa
variant_closed_gof_bluestarr_flank35_unobs.fa
variant_closed_gof_bluestarr.tsv.gz
variant_closed_gof_bluestarr_withseq_flank35.tsv.gz


**Check import**

In [6]:
### set directory
txt_fdiry = os.path.join(FD_RES, "analysis_variant_motif_richard")
txt_fname = "JASPAR2024_CORE_vertebrates_non-redundant.lods.npz"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import data
obj = np.load(txt_fpath, allow_pickle=True)

### show results
print("Keys:", obj.files)
print("Background:", obj["bg"])
print("Alphabet:", obj["alphabet"])
print("Number of motifs:", len(obj["names"]))
print("Example motif:", obj["names"][0])

Keys: ['pwms', 'lods', 'bg', 'names', 'alphabet']
Background: [0.31302372 0.18711331 0.18779196 0.312071  ]
Alphabet: ACGT
Number of motifs: 879
Example motif: MA0002.3 Runx1


In [7]:
type(obj["lods"])

numpy.ndarray

In [8]:
type(obj["lods"].item())

dict

In [9]:
type(obj["bg"])

numpy.ndarray

## Import data

**Check file existent**

In [3]:
%env FD_DATA={FD_DATA}

env: FD_DATA=/hpc/group/igvf/kk319/data


In [4]:
%%bash
ls ${FD_DATA}/jaspar2024

JASPAR2024_CORE_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_non-redundant_pfms_meme.zip
JASPAR2024_CORE_non-redundant_pfms_transfac.zip
JASPAR2024_CORE_vertebrates_meme
JASPAR2024_CORE_vertebrates_non-redundant.meme
JASPAR2024_CORE_vertebrates_non-redundant.npz
JASPAR2024_CORE_vertebrates_non-redundant_pfms_jaspar.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_meme.zip
JASPAR2024_CORE_vertebrates_non-redundant_pfms_transfac.zip


**Import data**

In [5]:
### set file directory
txt_fdiry = "/hpc/group/igvf/kk319/data/jaspar2024"
txt_fname = "JASPAR2024_CORE_vertebrates_non-redundant.npz"
#txt_fname = "JASPAR2024_CORE_vertebrates_non-redundant.meme"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### import data
data = np.load(txt_fpath, allow_pickle=True)

## Explore data

**Data type**

In [6]:
type(data)

numpy.lib.npyio.NpzFile

In [7]:
obj_motif_pwms = data["pwms"].item() # dict {name: (W,4)}
obj_motif_lods = data["lods"].item() # dict {name: (W,4)}
obj_motif_bg   = data["bg"]
vec_motif_name = data["names"]
txt_alphabet   = data["alphabet"]

print(type(obj_motif_pwms))
print(type(obj_motif_lods))
print(type(obj_motif_bg))
print(type(vec_motif_name))
print(type(txt_alphabet))

<class 'dict'>
<class 'dict'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**Meta data**

In [8]:
print("#{Motifs}: ", len(obj_motif_pwms), "motifs")
print("Alphabet:  ", txt_alphabet)
print("Background:", obj_motif_bg)
print("Motif name:")
print(vec_motif_name[:6], "...")

#{Motifs}:  879 motifs
Alphabet:   ACGT
Background: [0.25 0.25 0.25 0.25]
Motif name:
['MA0002.3 Runx1' 'MA0003.5 TFAP2A' 'MA0004.1 Arnt' 'MA0006.2 Ahr::Arnt'
 'MA0007.4 Ar' 'MA0009.2 TBXT'] ...


**Motif matrix**

In [9]:
txt_motif_name = "MA0002.3 Runx1"

print("Runx1 shape:", obj_motif_pwms[txt_motif_name].shape);     print()
print("Runx1 PWM:");      print(obj_motif_pwms[txt_motif_name]); print()
print("Runx1 log-odds:"); print(obj_motif_lods[txt_motif_name])

Runx1 shape: (9, 4)

Runx1 PWM:
[[0.0615 0.536  0.0745 0.328 ]
 [0.0285 0.     0.0035 0.968 ]
 [0.     0.0375 0.936  0.0265]
 [0.0435 0.0635 0.035  0.858 ]
 [0.     0.     0.9935 0.0065]
 [0.0085 0.021  0.924  0.0465]
 [0.005  0.2    0.1255 0.6695]
 [0.0655 0.2315 0.0405 0.6625]
 [0.25   0.079  0.1445 0.5265]]

Runx1 log-odds:
[[ -2.02326978   1.10030491  -1.74661576   0.39176772]
 [ -3.13289427 -17.93156857  -6.15842936   1.95307895]
 [-17.93156857  -2.73696559   1.90458043  -3.23786383]
 [ -2.52284079  -1.9770996   -2.83650127   1.77904955]
 [-17.93156857 -17.93156857   1.99059187  -5.26534457]
 [ -4.87832144  -3.57346686   1.88596476  -2.42662547]
 [ -5.64385619  -0.32192809  -0.99424073   1.42115596]
 [ -1.93236128  -0.1109159   -2.62593428   1.40599236]
 [  0.          -1.66200354  -0.7908586    1.07450544]]
